version: '3'

dotenv: [.env]

tasks:
  init:
    cmds:
      - src/initialize.sh {{.CLI_ARGS}} && cat .env

  prepare:
    cmds:
      - mkdir $DIR
      - src/backup.sh
      - src/list.sh $ENV
      - sshpass -p $PASS ssh $HOST "$WP config set WP_DEBUG true --raw --path=$WP_DIR"
      - sshpass -p $PASS ssh $HOST "$WP eval 'error_log(123456789);' --path=$WP_DIR"

  show:
    cmds:
      - src/show.sh

  update:
    cmds:
      - src/update.sh

  clean:
    cmds:
      - sshpass -p $PASS scp $DIR/wp-config.php $HOST:$WP_DIR/
      - sshpass -p $PASS scp $HOST:$WP_LOG_FILE $DIR/

  rmlog:
    cmds:
      - sshpass -p $PASS ssh $HOST "rm $WP_LOG_FILE"

  add:
    cmds:
      - touch env.json
      - jq -s add env.json env.json.example > tmpfile && mv tmpfile env.json

  ssh:
    cmds:
      - sshpass -p $PASS ssh $HOST {{.CLI_ARGS}}

  backup:
    - mkdir $DIR
    - src/backup.sh
    - src/list.sh $ENV
