version: '3'

dotenv: [.env]

tasks:
  init:
    cmds:
      - cp .env.example .env

  avant:
    cmds:
      - mkdir $DIR
      - src/backup.sh
      - src/list.sh $ENV
      - src/show.sh
      - sshpass -p $PASS ssh $HOST "$WP config set WP_DEBUG true --raw --path=$WP_DIR"
      - sshpass -p $PASS ssh $HOST "$WP eval 'error_log(123456789);' --path=$WP_DIR"

  update:
    cmds:
      - src/update.sh

  apres:
    cmds:
      - sshpass -p $PASS scp $DIR/wp-config.php $HOST:$WP_DIR/
      - sshpass -p $PASS scp $HOST:$WP_LOG_FILE $DIR/

  rmlog:
    cmds:
      - sshpass -p $PASS ssh $HOST "rm $WP_LOG_FILE"
